# Generated by Django 3.0.7 on 2020-06-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_2',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_3',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
        ),
    ]
