# Generated by Django 3.0.7 on 2020-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20200624_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('motorola', 'Motorola'), ('vivo', 'Vivo'), ('oppo', 'Oppo'), ('xiaomi', 'Xiaomi'), ('oneplus', 'Oneplus')], default=0, max_length=100),
        ),
    ]
