# Generated by Django 3.0.7 on 2020-06-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20200627_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('32', '32'), ('64', '64')], default=0, max_length=4),
        ),
    ]
